AWSTemplateFormatVersion: '2010-09-09'
Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
Outputs:
  BucketName:
    Value: !Ref 's3-bucket-ashok-cft'
    Description: Name of the sample Amazon S3 bucket.
